### ISSUE TITLE
Excalidraw color palette does not show colors

### ISSUE THREAD

**Issue by mogekag** [Jopp-gh/Obsidian-Dune84#24]
**Is your pull request related to a problem? Please describe**
Excalidraw color palette does not show colors when Dune84 is applied, light and dark themes alike.

**Describe the solution you'd like**
Color palette and color picker colors are visible both in light and dark themes.

**Screenshots**
![image](https://github.com/user-attachments/assets/8e9095c5-f9df-4890-b1d9-802a872e8ad3)
![image](https://github.com/user-attachments/assets/5f90ebe6-f524-4afa-814d-cdd76f48bac3)

**Workaround**
Do not apply to excalidraw:
https://github.com/Jopp-gh/Obsidian-Dune84/blob/4fe76bc493ea7e3190f848cef10b213a8f247eb6/theme.css#L2698
```css
.theme-dark button:not(.clickable-icon, .mod-cta, .mod-warning, .mod-destructive):not(.excalidraw *) {
    color: var(--text-normal);
    background-color: rgba(255, 255, 255, 0.1);
}

```

**Mobile: **

Device: Samsung Galaxy S9 Ultra
OS: OneUI
Version 6.0.1

**Desktop: **

OS: macos 
Version: Sequoia 15.1.1 (24B91)
